name: AnonSurf-build

on:
  push:
    branches: [ Remove-GUI ]
  
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Nim
      run: sudo apt-get update && sudo apt-get full-upgrade && sudo apt-get install nim
    
    - name: Build
      run: make build
