name: AnonSurf-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Nim
    - run: apt-get update && apt-get full-upgrade && apt-get install nim
    
    - name: configure
      run: ./configure
      
    - name: Install dependencies
      run: make
      
    - name: Build
      run: make build
